CREATE TABLE Person (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
fullname varchar(100) NOT NULL UNIQUE,
yearofbirth int NOT NULL,
login varchar(100) NOT NULL UNIQUE,
password varchar(100) NOT NULL,
role varchar(100)  NOT NULL
);
--password for all users is 123456
INSERT INTO person(fullname,yearOfBirth,login,password,role) VALUES
('Игнасиас Мигель Педрович',1990,'log1','$2a$10$T5GQc9gcPkmeCuKiYf4Nmu3G5/g59q7PwpTYUJtCDLwd5kuuT5YrK','ROLE_USER'),
('Иванов Иван Иванович',2008,'user1','$2a$10$T5GQc9gcPkmeCuKiYf4Nmu3G5/g59q7PwpTYUJtCDLwd5kuuT5YrK','ROLE_USER'),
('Махов Андрей Леонидович',1994,'user2','$2a$10$T5GQc9gcPkmeCuKiYf4Nmu3G5/g59q7PwpTYUJtCDLwd5kuuT5YrK','ROLE_USER'),
('Романов Антон Игоревич',1994,'user3','$2a$10$T5GQc9gcPkmeCuKiYf4Nmu3G5/g59q7PwpTYUJtCDLwd5kuuT5YrK','ROLE_USER'),
('Куцепко Вадим Афанасьевич',1995,'user4','$2a$10$T5GQc9gcPkmeCuKiYf4Nmu3G5/g59q7PwpTYUJtCDLwd5kuuT5YrK','ROLE_USER'),
('Петрова Елена Алексеевна',1991,'admin','$2a$10$T5GQc9gcPkmeCuKiYf4Nmu3G5/g59q7PwpTYUJtCDLwd5kuuT5YrK','ROLE_ADMIN');


CREATE TABLE Book (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title varchar(100) NOT NULL,
author varchar(100) NOT NULL,
year int NOT NULL,
person_id int REFERENCES Person(id) ON DELETE SET NULL,
hold_date timestamp
);

INSERT INTO book(title,author,year,person_id,hold_date) VALUES
('Алгоритмы: построение и анализ','Томас Кормен',1989,1,'2022-05-20 17:20:30.621000'),
('Java. Эффективное программирование','Джошуа Блох',2001,1,current_timestamp),
('Дюна','Фрэнк Герберт',1965,2,current_timestamp);
INSERT INTO book(title,author,year) VALUES
('Java 8','Шилдт Герберт',2014),
('Философия Java','Брюс Эккель',1998);

